version: '3.8'

services:
  db:
    container_name: infoware_mysql
    image: "mysql:${MYSQL_VERSION}"
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - network
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_HOST
      - MYSQL_ALLOW_EMPTY_PASSWORD
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password

  proxy_server:
    container_name: infoware_proxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PROXY_TARGET: 'http://api:6000'
    ports:
      - 8000:5000
    networks:
      - network
    volumes:
      - ./src:/src

  api:
    container_name: infoware
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8001:6000
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ./server:/server

volumes:
  mysql-data:

networks:
  network:
